# TODO
downloads: ~/.ansible-downloads/

# TODO
configure_dotfiles: false 
configure_terminal: false 
configure_osx: false 

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true 
dockitems_remove: 
  - TV
  - Musica
  - Safari
  - Mail
  - Mappe
  - Foto
  - FaceTime
  - Calendario
  - Contatti
  - Promemoria
  - Note
  - 'Preferenze di Sistema'
  - Podcasts
  - 'App Store'
dockitems_persist: 
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 4
  - name: "Alacritty"
    path: "/Applications/Alacritty.app/"
    pos: 5
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 6
  - name: "Proxyman"
    path: "/Applications/Proxyman.app/"
    pos: 7
  - name: "Spark"
    path: "/Applications/Spark.app/"
    pos: 8
  - name: "Cron"
    path: "/Applications/Cron.app/"
    pos: 9

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: true
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
# dotfiles_files:
#   - .zshrc
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

# SSH keys
ssh_keys:
  - src: "./.ssh/bb_id_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/bb_id_rsa"
  - src: "./.ssh/id_ed25519"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  - src: "./.ssh/gitkraken_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/gitkraken_rsa"
ssh_pub_keys:
  - src: "./.ssh/bb_id_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/bb_id_rsa.pub"
  - src: "./.ssh/id_ed25519.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  - src: "./.ssh/gitkraken_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/gitkraken_rsa.pub"
ssh_config:
  - src: "./.ssh/config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
  - src: "./.ssh/known_hosts"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - antigen
  - autoconf
  - bash-completion
  - bat
  - difftastic
  - duf
  - exa
  - fd
  - fzf
  - gettext
  - git
  - git-delta
  - ghq
  - go
  - httpie
  - htop
  - iperf
  - lazydocker
  - jesseduffield/lazydocker/lazydocker
  - libevent
  - sqlite
  - mas
  - mcrypt
  - neovim
  - nmap
  - node
  - peco
  - php
  - readline
  - ripgrep
  - openssl
  - shellcheck
  - shfmt
  - stow
  - pv
  - the_silver_searcher
  - thefuck
  - tmux
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - android-studio
  - balenaetcher
  - discord
  - docker
  - font-fira-code
  - font-inconsolata
  - firefox
  - gitkraken
  - google-chrome
  - keepingyouawake
  - meld
  - mounty
  - nordvpn
  - notion
  - postman
  - proxyman
  - qbittorrent
  - raycast
  - sequel-ace
  - simplenote
  - slack
  - spotify
  - stats
  - sublime-text
  - telegram-desktop
  - transmit
  - visual-studio-code
  - vlc
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
# mas_installed_apps: []
# mas_email: ""
# mas_password: ""

# osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
# npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
npm_packages:
  - name: tsc
    state: latest
  - name: fixjson
    state: latest
  - name: write-good
    state: latest
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
