# TODO
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
# if error, brew uninstall dockutil; brew install --cask hpedrorodrigues/tools/dockutil
dockutil_homebrew_cask: hpedrorodrigues/tools/dockutil
dockutil_install: false
dockitems_remove:
  - TV
  - Musica
  - Safari
  - Mail
  - Mappe
  - Foto
  - FaceTime
  - Calendario
  - Contatti
  - Promemoria
  - Note
  - 'Preferenze di Sistema'
  - Podcasts
  - 'App Store'
dockitems_persist:
  # - name: "Google Chrome"
  #   path: "/Applications/Google Chrome.app/"
  #   pos: 3
  # - name: "Firefox"
  #   path: "/Applications/Firefox.app/"
  #   pos: 4
  - name: "Alacritty"
    path: "/Applications/Alacritty.app/"
    pos: 1
  # - name: "Visual Studio Code"
  #   path: "/Applications/Visual Studio Code.app/"
  #   pos: 6
  # - name: "Proxyman"
  #   path: "/Applications/Proxyman.app/"
  #   pos: 7
  # - name: "Spark"
  #   path: "/Applications/Spark.app/"
  #   pos: 8
  # - name: "Cron"
  #   path: "/Applications/Cron.app/"
  #   pos: 9

# SSH keys
ssh_keys:
  - src: "./.ssh/bb_id_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/bb_id_rsa"
  - src: "./.ssh/id_ed25519"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  - src: "./.ssh/gitkraken_rsa"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/gitkraken_rsa"
ssh_pub_keys:
  - src: "./.ssh/bb_id_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/bb_id_rsa.pub"
  - src: "./.ssh/id_ed25519.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
  - src: "./.ssh/gitkraken_rsa.pub"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/gitkraken_rsa.pub"
ssh_config:
  - src: "./.ssh/config"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
  - src: "./.ssh/known_hosts"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - bat
  - bun
  - colima
  - commitizen
  - difftastic
  - docker
  - docker-completion
  - dua-cli
  - duf
  - eza
  - fd
  - fzf
  - gettext
  - ghq
  - git
  - git-delta
  - git-flow
  - go
  - htop
  - httpie
  - iperf
  - jandedobbeleer/oh-my-posh/oh-my-posh
  - lazydocker
  - lazygit
  - libevent
  - mas
  - mcrypt
  - mkcert
  - sqlite
  - neovim
  - nmap
  - node
  - nss
  - openssl@3
  - peco
  - php
  - pnpm
  - pv
  - release-it
  - ripgrep
  - readline
  - shellcheck
  - shfmt
  - stow
  - tailspin
  - the_silver_searcher
  - thefuck
  - tmux
  - wget
  - wrk
  - zoxide
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/bundle
  - jandedobbeleer/oh-my-posh
  - jesseduffield/lazydocker
  - jesseduffield/lazygit
  - oven-sh/bun

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alacritty
  - android-studio
  - balenaetcher
  - cyberduck
  - discord
  - firefox
  - fontbase
  - font-fira-code
  - font-hack-nerd-font
  - font-inconsolata
  - gas-mask
  - gimp
  - godot
  - google-chrome
  - inkscape
  - jdownloader
  - keepingyouawake
  - local # WP Development
  - mounty
  - nordvpn
  - notion
  - postman
  - proxyman
  - qbittorrent
  - raycast
  - responsively
  - slack
  - spotify
  - sublime-text
  - telegram-desktop
  - temurin
  - visual-studio-code
  - vlc
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
# mas_installed_apps: []
mas_installed_apps:
  - { id: 1102004240, name: "iHosts" }
  - { id: 472226235, name: "LanScan" }
  - { id: 409201541, name: "Pages" }
  - { id: 1176895641, name: "Spark" }
  - { id: 409183694, name: "Keynote" }
  - { id: 497799835, name: "Xcode" }
  - { id: 409203825, name: "Numbers" }
# mas_email: ""
# mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
# npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
npm_packages:
  - name: tsc
    state: latest
  - name: fixjson
    state: latest
  - name: write-good
    state: latest
  - name: ni
    state: latest
  - name: qnm
    state: latest
  - name: degit
    state: latest
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
