---

- name: Ensure .ssh directory exists.
  become_user: root
  file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Install ssh private keys
  become_user: root
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  loop: "{{ ssh_keys }}"
  tags:
    - ssh

- name: Install ssh public keys
  become_user: root
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  loop: "{{ ssh_pub_keys }}"
  tags:
    - ssh

- name: Install ssh config
  become_user: root
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  loop: "{{ ssh_config }}"
  tags:
    - ssh

- name: Set authorized key from file
  authorized_key:
    user: "ansible_user"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}.ssh/*.pub"

#
# - name: Set authorized key took from file
#   authorized_key:
#     user: "{{ lookup('env', 'USER') }}"
#     state: present
#     key: "{{ item.dest }}"
#   loop: "{{ ssh_pub_keys }}"
#   tags:
#     - ssh
